//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlannerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int task_id { get; set; }
        public int profile_id { get; set; }
        public string task_title { get; set; }
        public string task_description { get; set; }
        public System.DateTime task_date { get; set; }
        public Nullable<System.TimeSpan> task_time_start { get; set; }
        public Nullable<System.TimeSpan> task_time_end { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
